# Generated by Django 4.0.3 on 2022-03-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_memo_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('refund', 'refund'), ('confirmed', 'confirmed'), ('delivered', 'delivered')], default='pending', max_length=32),
        ),
    ]
